type RecordValue = Record<string, unknown>

type Props = { value: RecordValue; media: RecordValue[]; notes?: RecordValue[]; onChange: (value: RecordValue) => void }

const records = (value: unknown): RecordValue[] => Array.isArray(value) ? value.filter((item): item is RecordValue => Boolean(item) && typeof item === 'object' && !Array.isArray(item)) : []
const strings = (value: unknown): string[] => Array.isArray(value) ? value.map(String) : []

function Repeater({ title, items, template, fields, onChange }: { title: string; items: RecordValue[]; template: RecordValue; fields: Array<[string, string, 'text' | 'textarea' | 'number' | 'checkbox']>; onChange: (items: RecordValue[]) => void }) {
  const move = (index: number, offset: number) => { const next = [...items]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; onChange(next) }
  return <section><h3>{title}</h3>{items.map((item, index) => <div className="admin-about-card" key={index}><div className="admin-about-card__remove"><button type="button" onClick={() => move(index, -1)} disabled={index === 0}>↑</button><button type="button" onClick={() => move(index, 1)} disabled={index === items.length - 1}>↓</button><button type="button" onClick={() => onChange(items.filter((_, i) => i !== index))}>×</button></div><div className="admin-project-grid">{fields.map(([key, label, kind]) => <label key={key}><span>{label}</span>{kind === 'textarea' ? <textarea rows={3} value={String(item[key] ?? '')} onChange={(event) => onChange(items.map((current, i) => i === index ? { ...current, [key]: event.target.value } : current))} /> : kind === 'checkbox' ? <input type="checkbox" checked={Boolean(item[key])} onChange={(event) => onChange(items.map((current, i) => i === index ? { ...current, [key]: event.target.checked } : current))} /> : <input type={kind} value={kind === 'number' ? Number(item[key] ?? 0) : String(item[key] ?? '')} onChange={(event) => onChange(items.map((current, i) => i === index ? { ...current, [key]: kind === 'number' ? Number(event.target.value) : event.target.value } : current))} />}</label>)}</div></div>)}<button type="button" onClick={() => onChange([...items, { ...template }])}>+ Add {title.toLowerCase()}</button></section>
}

export default function ProjectEditor({ value, media, notes = [], onChange }: Props) {
  const images = media.filter((item) => String(item.mime_type).startsWith('image/'))
  const extra = value.extra && typeof value.extra === 'object' && !Array.isArray(value.extra) ? value.extra as RecordValue : {}
  const trace = value.trace && typeof value.trace === 'object' && !Array.isArray(value.trace) ? value.trace as RecordValue : {}
  const sections = records(value.sections)
  const set = (key: string, next: unknown) => onChange({ ...value, [key]: next })
  const setExtra = (key: string, next: unknown) => set('extra', { ...extra, [key]: next })
  const setTrace = (key: string, next: unknown) => set('trace', { ...trace, [key]: next })
  const section = (id: string) => sections.find((item) => item.id === id) ?? { id, title: id[0].toUpperCase() + id.slice(1), body: '' }
  const setSection = (id: string, patch: RecordValue) => { const exists = sections.some((item) => item.id === id); set('sections', exists ? sections.map((item) => item.id === id ? { ...item, ...patch } : item) : [...sections, { ...section(id), ...patch }]) }
  const selectMedia = (label: string, id: string, onSelect: (asset: RecordValue | null) => void) => <label><span>{label}</span><select value={id} onChange={(event) => onSelect(images.find((item) => item.id === event.target.value) ?? null)}><option value="">No image selected</option>{images.map((item) => <option value={String(item.id)} key={String(item.id)}>{String(item.filename)}</option>)}</select>{id && images.find((item) => item.id === id) && <div className="admin-project-media-preview"><img src={String(images.find((item) => item.id === id)?.public_url)} alt="Selected media" /></div>}</label>

  const problem = section('problem'); const system = section('system')
  return <div className="admin-project-editor">
    <section><h3>Project card & identity</h3><div className="admin-project-grid">{[['title','Title'],['slug','Slug'],['index_label','Index label'],['domain','Domain'],['status','Status'],['year','Year']].map(([key,label]) => <label key={key}><span>{label}</span><input value={String(value[key] ?? '')} onChange={(event) => set(key, key === 'slug' ? event.target.value.toLowerCase().replace(/[^a-z0-9-]+/g, '-') : event.target.value)} /></label>)}<label><span>Sort order</span><input type="number" value={Number(value.sort_order ?? 0)} onChange={(event) => set('sort_order', Number(event.target.value))} /></label></div><div className="admin-project-checks"><label><input type="checkbox" checked={Boolean(value.featured)} onChange={(event) => set('featured', event.target.checked)} /> Featured</label><label><input type="checkbox" checked={Boolean(value.published)} onChange={(event) => set('published', event.target.checked)} /> Published</label></div></section>
    <section><h3>Project story</h3>{[['question','Card question',3],['thesis','Detail-page thesis',3],['summary','Long description',5]].map(([key,label,rows]) => <label key={String(key)}><span>{label}</span><textarea rows={Number(rows)} value={String(value[String(key)] ?? '')} onChange={(event) => set(String(key), event.target.value)} /></label>)}</section>
    <section><h3>Media & captions</h3><div className="admin-project-media-grid">{selectMedia('Card cover', String(value.cover_media_id ?? ''), (asset) => set('cover_media_id', asset?.id ?? null))}{selectMedia('Hero image', String(extra.hero_media_id ?? ''), (asset) => set('extra', { ...extra, hero_media_id: asset?.id ?? null, hero_url: asset?.public_url ?? null, hero_alt: asset?.alt_text ?? null }))}{selectMedia('Problem plate', String(problem.media_id ?? ''), (asset) => setSection('problem', { media_id: asset?.id ?? null, media_url: asset?.public_url ?? null, media_alt: asset?.alt_text ?? null }))}{selectMedia('System plate', String(system.media_id ?? ''), (asset) => setSection('system', { media_id: asset?.id ?? null, media_url: asset?.public_url ?? null, media_alt: asset?.alt_text ?? null }))}</div>{[['hero_caption','Hero caption'],['hero_credit','Hero photo credit'],['plate_caption','Problem plate caption']].map(([key,label]) => <label key={key}><span>{label}</span><input value={String(extra[key] ?? '')} onChange={(event) => setExtra(key, event.target.value)} /></label>)}</section>
    <Repeater title="Metrics" items={records(value.metrics)} template={{ value: '', label: '' }} fields={[["value","Value","text"],["label","Label","text"]]} onChange={(items) => set('metrics', items)} />
    <Repeater title="Pipeline steps" items={records(value.pipeline)} template={{ label: '', state: '' }} fields={[["label","Label","text"],["state","State (complete/skipped/decision)","text"]]} onChange={(items) => set('pipeline', items)} />
    <section><h3>Problem</h3><label><span>Title</span><input value={String(problem.title ?? '')} onChange={(event) => setSection('problem', { title: event.target.value })} /></label><label><span>Copy</span><textarea rows={5} value={String(problem.body ?? '')} onChange={(event) => setSection('problem', { body: event.target.value })} /></label></section>
    <section><h3>System</h3><label><span>Title</span><input value={String(system.title ?? '')} onChange={(event) => setSection('system', { title: event.target.value })} /></label><label><span>Copy</span><textarea rows={5} value={String(system.body ?? '')} onChange={(event) => setSection('system', { body: event.target.value })} /></label><label><span>System nodes — comma separated</span><input value={strings(extra.system_nodes).join(', ')} onChange={(event) => setExtra('system_nodes', event.target.value.split(',').map((item) => item.trim()).filter(Boolean))} /></label></section>
    <Repeater title="Build stages" items={records(extra.stages)} template={{ index: '', label: '', title: '', detail: '', state: '' }} fields={[["index","Index","text"],["label","Label","text"],["title","Title","text"],["detail","Detail","textarea"],["state","Link/state label","text"]]} onChange={(items) => setExtra('stages', items)} />
    <section><h3>Evidence terminal</h3><label><span>Section introduction</span><textarea rows={3} value={String(extra.evidence_copy ?? '')} onChange={(event) => setExtra('evidence_copy', event.target.value)} /></label><div className="admin-project-grid"><label><span>Command</span><input value={String(trace.cmd ?? '')} onChange={(event) => setTrace('cmd', event.target.value)} /></label><label><span>Result</span><input value={String(trace.result ?? '')} onChange={(event) => setTrace('result', event.target.value)} /></label></div></section>
    <Repeater title="Evidence rows" items={records(trace.rows)} template={{ k: '', v: '', note: '', w: 0, hi: false }} fields={[["k","Key","text"],["v","Value","text"],["note","Note","text"],["w","Bar (0–1)","number"],["hi","Highlight","checkbox"]]} onChange={(items) => setTrace('rows', items)} />
    <Repeater title="Verification checks" items={records(extra.checks)} template={{ label: '', status: 'Pass' }} fields={[["label","Check","text"],["status","Status","text"]]} onChange={(items) => setExtra('checks', items)} />
    <section><h3>Related Field Notes</h3><p>Select notes shown at the bottom of this project.</p>{notes.map((note) => { const selected = strings(extra.related_note_slugs); const slug = String(note.slug); return <label className="admin-project-checks" key={slug}><input type="checkbox" checked={selected.includes(slug)} onChange={(event) => { const slugs = event.target.checked ? [...selected, slug] : selected.filter((item) => item !== slug); set('extra', { ...extra, related_note_slugs: slugs, related_notes: notes.filter((candidate) => slugs.includes(String(candidate.slug))).map((candidate) => ({ title: candidate.title, meta: candidate.note_type || 'Field note', href: `/field-notes/${String(candidate.slug)}` })) }) }} /> {String(note.title)}</label> })}</section>
    <section><h3>Navigation & SEO</h3><div className="admin-project-grid">{[['current','Current label'],['next','Next label'],['nextHref','Next URL'],['seo_title','SEO title'],['seo_description','SEO description']].map(([key,label]) => <label key={key}><span>{label}</span><input value={String(extra[key] ?? '')} onChange={(event) => setExtra(key, event.target.value)} /></label>)}</div></section>
  </div>
}
