import { useState } from 'react'

type RecordValue = Record<string, unknown>
type Mode = 'note' | 'profile' | 'setting' | 'page'

type Props = {
  mode: Mode
  value: RecordValue
  media: RecordValue[]
  onChange: (value: RecordValue) => void
}

function JsonField({ label, value, onChange }: { label: string; value: unknown; onChange: (value: unknown) => void }) {
  const [text, setText] = useState(() => JSON.stringify(value ?? {}, null, 2))
  const [error, setError] = useState('')
  return <label className="admin-structured__wide"><span>{label} · advanced</span><textarea rows={8} value={text} onChange={(event) => { const next = event.target.value; setText(next); try { onChange(JSON.parse(next)); setError('') } catch { setError('Invalid JSON') } }} spellCheck={false} />{error && <small className="admin-structured__error">{error}</small>}</label>
}

export default function StructuredRecordEditor({ mode, value, media, onChange }: Props) {
  const set = (key: string, next: unknown) => onChange({ ...value, [key]: next })
  const images = media.filter((item) => String(item.mime_type).startsWith('image/'))
  const imageSelect = (label: string, key: string) => <label><span>{label}</span><select value={String(value[key] ?? '')} onChange={(event) => set(key, event.target.value || null)}><option value="">No image selected</option>{images.map((item) => <option value={String(item.id)} key={String(item.id)}>{String(item.filename)}</option>)}</select></label>

  if (mode === 'note') return <div className="admin-structured"><section><h3>Field Note</h3><div className="admin-structured__grid"><label><span>Title</span><input value={String(value.title ?? '')} onChange={(event) => set('title', event.target.value)} /></label><label><span>Slug</span><input value={String(value.slug ?? '')} onChange={(event) => set('slug', event.target.value.toLowerCase().replace(/[^a-z0-9-]+/g, '-'))} /></label><label><span>Type</span><input value={String(value.note_type ?? '')} onChange={(event) => set('note_type', event.target.value)} /></label><label><span>Related project slug</span><input value={String(value.project_slug ?? '')} onChange={(event) => set('project_slug', event.target.value || null)} /></label><label><span>Reading minutes</span><input type="number" min={1} value={Number(value.reading_minutes ?? 1)} onChange={(event) => set('reading_minutes', Number(event.target.value))} /></label>{imageSelect('Cover image', 'cover_media_id')}</div><div className="admin-structured__checks"><label><input type="checkbox" checked={Boolean(value.featured)} onChange={(event) => set('featured', event.target.checked)} /> Featured</label><label><input type="checkbox" checked={Boolean(value.published)} onChange={(event) => set('published', event.target.checked)} /> Published</label></div><label className="admin-structured__wide"><span>Excerpt</span><textarea rows={3} value={String(value.excerpt ?? '')} onChange={(event) => set('excerpt', event.target.value)} /></label><label className="admin-structured__wide"><span>Body</span><textarea rows={12} value={String(value.body ?? '')} onChange={(event) => set('body', event.target.value)} /></label><label className="admin-structured__wide"><span>Tags — comma separated</span><input value={Array.isArray(value.tags) ? value.tags.join(', ') : ''} onChange={(event) => set('tags', event.target.value.split(',').map((item) => item.trim()).filter(Boolean))} /></label><JsonField label="Structured content blocks" value={value.content_blocks ?? []} onChange={(next) => set('content_blocks', next)} /></section></div>

  if (mode === 'profile') return <div className="admin-structured"><section><h3>Profile</h3><div className="admin-structured__grid"><label><span>Name</span><input value={String(value.name ?? '')} onChange={(event) => set('name', event.target.value)} /></label><label><span>Role</span><input value={String(value.role ?? '')} onChange={(event) => set('role', event.target.value)} /></label><label><span>Location</span><input value={String(value.location ?? '')} onChange={(event) => set('location', event.target.value)} /></label><label><span>Email</span><input type="email" value={String(value.email ?? '')} onChange={(event) => set('email', event.target.value || null)} /></label><label><span>Résumé URL</span><input type="url" value={String(value.resume_url ?? '')} onChange={(event) => set('resume_url', event.target.value || null)} /></label>{imageSelect('Profile image', 'avatar_media_id')}</div><label className="admin-structured__wide"><span>Headline</span><textarea rows={3} value={String(value.headline ?? '')} onChange={(event) => set('headline', event.target.value)} /></label><label className="admin-structured__wide"><span>Biography</span><textarea rows={7} value={String(value.biography ?? '')} onChange={(event) => set('biography', event.target.value)} /></label><JsonField label="Social links" value={value.social_links ?? []} onChange={(next) => set('social_links', next)} /><JsonField label="Additional profile data" value={value.extra ?? {}} onChange={(next) => set('extra', next)} /></section></div>

  if (mode === 'setting') return <div className="admin-structured"><section><h3>Site Setting</h3><div className="admin-structured__grid"><label><span>Key</span><input value={String(value.key ?? '')} readOnly /></label><label><span>Description</span><input value={String(value.description ?? '')} onChange={(event) => set('description', event.target.value)} /></label></div><div className="admin-structured__checks"><label><input type="checkbox" checked={Boolean(value.is_public)} onChange={(event) => set('is_public', event.target.checked)} /> Public setting</label></div>{typeof value.value === 'string' || typeof value.value === 'number' || typeof value.value === 'boolean' ? <label className="admin-structured__wide"><span>Value</span><textarea rows={5} value={String(value.value ?? '')} onChange={(event) => set('value', event.target.value)} /></label> : <JsonField label="Value" value={value.value} onChange={(next) => set('value', next)} />}</section></div>

  return <div className="admin-structured"><section><h3>Page Section</h3><div className="admin-structured__grid"><label><span>Page</span><select value={String(value.page ?? 'home')} onChange={(event) => set('page', event.target.value)}>{['home','work','field-notes','about','contact','footer'].map((page) => <option key={page}>{page}</option>)}</select></label><label><span>Section key</span><input value={String(value.section ?? '')} onChange={(event) => set('section', event.target.value.toLowerCase().replace(/[^a-z0-9_]+/g, '_'))} /></label><label><span>Sort order</span><input type="number" value={Number(value.sort_order ?? 0)} onChange={(event) => set('sort_order', Number(event.target.value))} /></label></div><div className="admin-structured__checks"><label><input type="checkbox" checked={Boolean(value.enabled)} onChange={(event) => set('enabled', event.target.checked)} /> Enabled</label></div><JsonField label="Section content" value={value.content ?? {}} onChange={(next) => set('content', next)} /></section></div>
}
